    local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/scripterhub/UILibraries/main/Xenon/Lib.lua", true))()
    library:CreateWatermark("Watermark")
    local Window = library:CreateWindow("Window Name",Enum.KeyCode.RightControl)
    local Tab = Window:CreateTab("TAB")
    local Sector1 = Tab:CreateSector("SECTOR","left")
    Sector1:AddLabel("LABEL")
    Sector1:AddToggle("TOGGLE",false,function(t)
       print(t)
    end)
    Sector1:AddButton("BUTTON",function()
        print("CENTERHUB")
    end)
    Sector1:AddDropdown("Multi DropdownText",{"None","IDK","odl2"},"None",true,function(t)
        print(t)
    end)
    Sector1:AddDropdown("DropdownText",{"None","IDK","odl2"},"None",false,function(t)
        print(t)
    end)
    local Dropdownxd = Sector1:AddToggle("Toggle With Dropdown",false,function(t)
       print(t)
    end)
    Dropdownxd:AddDropdown({"None","IDK","odl2"},"None",false,function(t)
        print(t)
    end)
    local Dropdow2nxd = Sector1:AddToggle("Toggle With Dropdown Multi",false,function(t)
       print(t)
    end)
    Dropdow2nxd:AddDropdown({"None","IDK","odl2"},"None",true,function(t)
        print(t)
    end)
    local Sector2 = Tab:CreateSector("Sector","Right")
     tablexd = {"xd1","table2","pussy3"}
    local dropdoxwn = Sector2:AddDropdown("DropdownText Select Weapon",tablexd,"None",false,function(t)
        print(t)
    end)
    Sector2:AddButton("Refresh Test",function()
        table.clear(tablexd)
        for i,v in pairs(tablexd) do
        dropdoxwn:Add(v)
        end
    end)
    local Sector3 = Tab:CreateSector("SECTOR 3","Right")
    Sector3:AddSlider("Slider By Center",20,50,100,1,function(x)
        print(x)
    end)
    local Sector4 = Tab:CreateSector("SECTOR 4","left")
    Sector4:AddColorpicker('Color picker',Color3.fromRGB(255, 255, 255),function(t)
        print(t)
    end)
    Sector3:AddSeperator("Seperator")
    local Tab2 = Window:CreateTab("Config")
    Tab2:CreateConfigSystem()